### ISSUE TITLE
deletedCDs is not declared in /objects/user.php

### ISSUE THREAD

**Issue by Sleepcap** [kestasjk/webDiplomacy#84] opened 2015-02-01 15:59 UTC
That throws an error message...

**Comment by TimothyJones** [comment] 2015-02-02 09:11
I think this is probably caused by #83. Let's fix that first, then re-confirm.

**Comment by TimothyJones** [comment] 2015-02-02 09:53
This should be fixed in the most recent commit. I'm going to optimistically close it - please reopen if it's not fixed.

**Closed by TimothyJones** 2015-02-02 09:53 UTC
Labels: Bug
