### ISSUE TITLE
Error while registering new player

### ISSUE THREAD

**Issue by mfontecilla** [kestasjk/webDiplomacy#255] opened 2017-06-28 20:57 UTC
Hi guys, hope you're doing well. A friend of mine is having issues opening an account. We want to start a 7 player private game and it is going to be his first one, however, while trying to "validate" his email on the Register tab, the Anti-bot or the email address validation does not seem to work as it keeps on displaying "Mailer error: SMTP Error: Could not authenticate.".  

He tried registering with both of his personal emails and between us tried helping him register on at least 4 different computers, all with the same error displayed. 

Do you guys know something about this and how to solve it so we can start playing?

**Comment by jcproctor29** [comment] 2017-06-29 08:47
I'm having the same problem. Can't register new accounts. This worked a week ago but was broken as of yesterday.

**Comment by TimothyJones** [comment] 2017-06-30 04:10
Thanks for bringing this to our attention. Looks like the email account we send mail from had somehow become disabled.

I've re-enabled it, but it may be a problem again in the future. I'll open another issue to move away from this way of sending email.

It should be fixed now.

**Comment by TimothyJones** [comment] 2017-06-30 04:34
The problem was probably caused by the forwarding from the gamemaster account to the monitoring account being broken, resulting in a lot of bounces (and potentially a suspicious activity flag).

I'm closing this for now. Please re-open it if it is not fixed for you.

**Closed by TimothyJones** 2017-06-30 04:34 UTC
